# Generated by Django 5.0.6 on 2024-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('client_ip', models.TextField()),
                ('location', models.TextField()),
                ('greetings', models.TextField()),
            ],
        ),
    ]
